#!/bin/bash

#sourch and call depends()
source userspace


######################################################
#################Verify our DHCP and bridge needs################
######################################################

dhcp()
{
    [[ $BRIDGED != 'True' ]] && dhcpcd -f ${DIR_CONF}dhcpd.conf -pf /var/run/dhcpcd.pid $AP || dhcpcd -cf ${DIR_CONF}dhcpd.conf -pf /var/run/dhcpcd.pid $BRIDGE_NAME

}
depends
dhcp