#!/bin/bash
if [[ $(id -u) != 0 ]]; then # Verify we are root if not exit
   echo "Please Run This Script As Root or With Sudo!" 1>&2
   exit 1
fi

SESSIONFOLDER=/tmp/n4p/
DIR_CONF=/etc/n4p/
DIR_LOGO=/usr/share/n4p/

get_name()
{
    USE=$(grep $1 ${DIR_CONF}n4p.conf | awk -F= '{print $2}')
}

get_state() # Retrieve the state of interfaces
{
    STATE=$(ip addr list | grep -i $1 | grep -i DOWN | awk -Fstate '{print $2}' | cut -d ' ' -f 2)
}
# Text color variables
BLD_PUR=${txtbld}$(tput setaf 5) # purple
BLD_TEA=${txtbld}$(tput setaf 6) # teal
TXT_RST=$(tput sgr0)             # Reset
WARN="${BLD_TEA}[${TXT_RST}${BLD_PUR} * ${TXT_RST}${BLD_TEA}]${TXT_RST}"
get_name "IFACE1="; IFACE1=$USE
get_name "VICTIM_BSSID="; VICTIM_BSSID=$USE
get_name "CHAN="; CHAN=$USE
MON="${IFACE1}mon"

do_it()
{
    if [[ -z $(ip addr | grep -i "${MON}") ]]; then
        iwconfig $IFACE1 mode monitor # Force managed mode upon wlan because airmon wont do this
        [[ -z $(ip addr | grep -i "${MON}") ]] && airmon-ng start $IFACE1
    fi

    if [[ -f ${SESSIONFOLDER}${VICTIM_BSSID}* ]]; then #verify file integritys
        read -p "${VICTIM_BSSID}*.cap exists already. Continuing will remove the file. Continue anyways? [y/n]" option
        if [[ $option != [Yy] ]]; then
            exit 1
        else
           rm ${SESSIONFOLDER}${VICTIM_BSSID}*
        fi
    fi
    #xterm -hold -bg black -fg blue -T "Dump" -geometry 90x20 -e airodump-ng --bssid $VICTIM_BSSID -c $CHAN --output-format pcap -w ${SESSIONFOLDER}$VICTIM_BSSID $MON &>/dev/null &
    xterm -bg black -fg DodgerBlue1 -T "Dump" -geometry 90x20 -e "bash -ic \"airodump-ng --bssid $VICTIM_BSSID -c $CHAN --output-format pcap -w ${SESSIONFOLDER}$VICTIM_BSSID $MON ; bash\"" &>/dev/null &
    keepalive
}

trap killAll INT HUP;
keepalive()
{
    read -p "$WARN Press ctrl^c when you are ready to go down!" ALLINTHEFAMILY # Protect this script from going down hastily
    [[ $ALLINTHEFAMILY != 'SGFjayBUaGUgUGxhbmV0IQ==' ]] && clear; keepalive
}

killAll()
{
    airmon-ng stop $MON
    echo "${BLD_TEA}$(cat ${DIR_LOGO}die.logo)${TXT_RST}"
    sleep 2
    exit 0
}
do_it
