#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [[ -h "$SOURCE" ]]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it's relativeness to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
source ${DIR}/userspace
source ${DIR}/airmon
depends
do_it
do_it_check
xterm -bg black -fg DodgerBlue1 -T "Dump" -geometry 90x20 -e "bash -ic \"airodump-ng --bssid $VICTIM_BSSID -c $CHAN --output-format pcap -w ${SESSIONFOLDER}$VICTIM_BSSID $MON ; bash\"" &>/dev/null &
keepalive