#!/bin/bash
###############################################
# Do all prerun variables and safety measures #
# before anything else starts happening       #
###############################################
#source and call depends()
source userspace #view this file for functions and variables you may use
depends


# This statement will allow you to add your custom variables for each of your modules and appened them into the config file for the user on first run
if [[ -z $(grep MY_CUSTOM_VARIABLE= ${DIR_CONF}n4p.conf) ]]; then #User module custom variable does not exist yet in our config. Add it now
    echo "MY_CUSTOM_VARIABLE=DefaultValue" >> ${DIRCONF}n4p.conf
    echo "Please adjust all needed variables in the n4p.conf file and then run this module again."
    sleep 6
    exit 0
fi

#grab custom variables you set in the n4p.conf file
get_name "MY_CUSTOM_VARIABLE="; MY_CUSTOM_VARIABLE=$USE


echo "My custom module!!!!!"
