#!/bin/bash
###############################################
# Do all prerun variables and safety measures #
# before anything else starts happening       #
###############################################
source userspace
depends
hostapd $HOSTAPD_CONFIG
