#!/bin/bash
nm_check() # Some wireless cards have issues dropping the module driver with NM, we have to cycle nm to reprobe the module
{
  if [[ $NETWORKMANAGER == "True" ]]; then
    if [[ $OS == "Pentoo" ]]; then
      if [[ -f /etc/init.d/NetworkManager ]]; then
        sudo /etc/init.d/NetworkManager restart
        sleep 7
        sudo /etc/init.d/NetworkManager stop
        sleep 2
      else
        echo "Error in Config file. NetworkManager does not appear to be present."
      fi
    else # were not using pentoo kill nm for systemd
      if [[ -f /etc/init.d/network-manager ]]; then
        sudo service network-manager stop
        sudo service networ-kmanager start
        sudo service network-manager stop
      fi
    fi
  elif [[ $OS == "Pentoo" ]]; then #Gentoo is making changes. This may not always work anymore.
      if [[ -e /etc/init.d/net.$IFACE1 ]]; then
          echo "$INFO I'm having issues with $IFACE1"
      fi
  fi
}

do_it_check() # add checks for kali people
{
    # Some wireless cards have issues dropping the module driver with NM, we have to cycle nm to reprobe the module. This loop checks if the adapter was succesfull going into monitor mode or not and then generates the processes over again if it wasn't.
    while [[ -z $(ip addr list | grep $MON) ]]; do
      echo -e "${BLD_TEA}Waiting for monitor interface to come up\n${TXT_RST}"
      echo "Attempt $IFACEBUG"  
      sleep 3
      if [[ $IFACEBUG == '2' || $IFACEBUG == '5' || $IFACEBUG == '14' || $IFACEBUG == '18' ]]; then
        nm_check
        if [[  $IFACEBUG == '9' || $IFACEBUG == '16' ]]; then # NM May be hung, Go to hell NetworkManager
          kill -9 $(ps -A | grep NetworkManager | awk -F' ' '{print $1}')
        fi
      fi

      if [[ $IFACEBUG == "20" ]]; then
        echo "${WARN}There appears to be a problem creating the monitor interface. You need to investigate. The following output may help. ${TXT_RST}"
        iw "$IFACE1" list
        sleep 7
        exit 2
      fi
      IFACEBUG=$((IFACEBUG + 1))
    done
}

if [[ $NETWORKMANAGER == "True" ]]; then #n4p cant operate airmon and such with network manager hogging everything. We must kill it.
    if [[ $OS == "Pentoo" ]]; then
        if [[ -f /etc/init.d/NetworkManager ]]; then
            get_RCstatus "NetworkManager"
            [[ $STATUS != 'stoped' ]] && sudo /etc/init.d/NetworkManager stop
        else
            echo "Error in Config file. NetworkManager does not appear to be present."
        fi
    else # were not using pentoo kill nm for systemd
        if [[ -f /etc/init.d/network-manager ]]; then
            sudo service network-manager stop
        fi
    fi
elif [[ $OS == "Pentoo" ]]; then
  if [[ -e /etc/init.d/net.$IFACE1 ]]; then
    #echo "$INFO Getting status of $IFACE1"
    get_RCstatus "net.$IFACE1"
    [[ $STATUS == 'started' ]] && /etc/init.d/net.$IFACE1 stop
  fi
fi