#!/bin/bash
BLD_RED=${txtbld}$(tput setaf 1) # red
BLD_TEA=${txtbld}$(tput setaf 6) # teal
TXT_RST=$(tput sgr0)             # Reset

DIR_LOGO=/usr/share/n4p/
LOG_METALOG=/var/log/everything/current
LOG_SYSLOG_NG=/var/log/dhcpd.log

echo "${BLD_TEA}$(cat ${DIR_LOGO}/monitor.logo)${TXT_RST}"

#if [[ -f $LOG_METALOG ]]; then
#    USE=$LOG_METALOG
#elif [[ -f $LOG_SYSLOG_NG ]]; then
#    USE=$LOG_SYSLOG_NG
#else
    echo "We were unable to locate any system log files\nPlease fix or use a different mode"
fi

#tail -f $USE | grep at0 | awk -FDHCPACK '{print $2}' | awk -Fvia '{print $1}'
tail -f /var/log/dhcpd.log