#!/bin/bash
source userspace


rebuild_network()
{
    if [[ -n $(ip addr | grep -i "$MON") ]]; then echo "$WARN Leftover scoobie snacks found! nom nom"; airmon-ng stop $MON; fi

    if [[ $BRIDGED == "True" ]]; then # All of this is deprecated update it asap.
        get_RCstatus "net.$BRIDGE_NAME"
        [[ $STATUS == 'started' ]] && /etc/init.d/net.$BRIDGE_NAME stop

        get_state "$BRDIGE"
        [[ $STATE != 'DOWN' ]] && ip link set $BRDIGE down

        brctl delif "$BRIDGE_NAME $RESP_BR_1"
        brctl delif "$BRIDGE_NAME $RESP_BR_2"
        brctl delbr "$BRIDGE_NAME"
        brctl show
    fi

    echo "$INFO It's now time to bring your default network interface back up"
    if [[ $NETWORKMANAGER != "True" ]]; then
        get_RCstatus "net.$IFACE0"
        if [[ $STATUS != 'started' ]]; then
            get_state "$IFACE0"
            [[ $STATE == 'DOWN' ]] && ip link set $IFACE0 up
            /etc/init.d/net.$IFACE0 start
        fi
        echo -e "\n$INFO The environment is now sanitized cya"
    else
        if [[ $OS == "Pentoo" ]]; then
            [[ $(get_RCstatus NetworkManager) != 'started' || $STATUS == 'inactive' ]] && /etc/init.d/NetworkManager start
        else
            service network-manager start
        fi
            echo -e "\n$INFO The environment is now sanitized cya"
    fi
    exit 0
}
depends
rebuild_network