#!/bin/bash
#retrieve absolute path structures so we can use symlinks and config files
SOURCE="${BASH_SOURCE[0]}"
while [[ -h "$SOURCE" ]]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it's relativeness to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

source ${DIR}/userspace
source ${DIR}/airmon

echo "${BLD_TEA}$(cat ${DIR_LOGO}recon.logo)${TXT_RST}"; sleep 2.5

recon()
{
    #/bin/sh -c "/usr/bin/launch '/usr/sbin/airmon-ng' 'start' 'wlan1mon' 'sudo -s'"
    #xterm -hold -bg black -fg blue -T "Recon" -geometry 90x20 -e airodump-ng ${MON} &>/dev/null &
    xterm -bg black -fg DodgerBlue1 -T "Recon" -geometry 90x20 -e "bash -ic \"airodump-ng ${MON} ; bash\"" &>/dev/null &
}

keepalive()
{
    read -p "$WARN Press ctrl^c when you are ready to go down!${TXT_RST}" ALLINTHEFAMILY # Protect this script from going down hastily
    [[ $ALLINTHEFAMILY != 'SGFjayBUaGUgUGxhbmV0IQ==' ]] && clear; keepalive
}

killAll()
{
    airmon-ng stop $MON
    echo "${BLD_TEA}$(cat ${DIR_LOGO}die.logo)${TXT_RST}"
    sleep 3
    exit 0
}

trap killAll INT HUP;
depends
do_it
do_it_check
recon
keepalive