#!/bin/bash
if [[ $(id -u) != 0 ]]; then # Verify we are root if not exit
   echo "Please Run This Script As Root or With Sudo!" 1>&2
   exit 1
fi

#retrieve absolute path structures so we can use symlinks and config files
SOURCE="${BASH_SOURCE[0]}"
while [[ -h "$SOURCE" ]]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="${DIR}/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it's relativeness to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
DIR_CONF=/etc/n4p
DIR_LOGO=/usr/share/n4p

get_name()
{
    USE=$(grep $1 ${DIR_CONF}/n4p.conf | awk -F= '{print $2}')
}

get_state() # Retrieve the state of interfaces
{
    STATE=$(ip addr list | grep -i $1 | grep -i DOWN | awk -Fstate '{print $2}' | cut -d ' ' -f 2)
}

get_name "VICTIM_BSSID="; VICTIM_BSSID=$USE
get_name "CHAN="; CHAN=$USE
get_name "LOCAL_BSSID="; LOCAL_BSSID=$USE
get_name "IFACE1="; IFACE1=$USE
MON="${IFACE1}mon"
IFACEBUG="0"
# Text color variables
TXT_BLD=$(tput bold)             # Bold
BLD_PUR=${txtbld}$(tput setaf 5) # purple
BLD_TEA=${txtbld}$(tput setaf 6) # teal
BLD_RED=${txtbld}$(tput setaf 1) # red
TXT_RST=$(tput sgr0)             # Reset
WARN="${BLD_TEA}[${TXT_RST}${BLD_PUR} * ${TXT_RST}${BLD_TEA}]${TXT_RST}"

echo "${BLD_TEA}$(cat ${DIR_LOGO}/recon.logo)${TXT_RST}"; sleep 2.5

[[ -n $(rfkill list | grep yes) ]] && rfkill unblock wlan

do_it()
{
    if [[ -z $(ip addr | grep -i "$MON") ]]; then
        iwconfig "$IFACE1" mode monitor #push $iface1 into monitor mode
        [[ -z $(ip addr | grep -i "$MON") ]] && airmon-ng start $IFACE1
    fi
    do_it_check
}

do_it_check()
{
    while [[ -z $(ip addr list | grep $MON) ]]; do
      echo -e "Waiting for monitor interface to come up\n" #add a counter so we can escape from this loop in future
      sleep 1
      if [[ $IFACEBUG == '4' ]]; then
        sudo /etc/init.d/NetworkManager restart
        sudo /etc/init.d/NetworkManager stop
        do_it
      fi

      if [[ $IFACEBUG == "9" ]]; then
        echo "There appears to be a problem creating the monitor interface. You need to investigate"
        sleep 5
        exit 2
      fi
      IFACEBUG=$((IFACEBUG + 1))
    done
    #/bin/sh -c "/usr/bin/launch '/usr/sbin/airmon-ng' 'start' 'wlan1mon' 'sudo -s'"
    xterm -hold -bg black -fg blue -T "Recon" -geometry 90x20 -e airodump-ng ${MON} &>/dev/null &
    keepalive
}

trap killAll INT HUP;
keepalive()
{
    read -p "$WARN Press ctrl^c when you are ready to go down!" ALLINTHEFAMILY # Protect this script from going down hastily
    [[ $ALLINTHEFAMILY != 'SGFjayBUaGUgUGxhbmV0IQ==' ]] && clear; keepalive
}

killAll()
{
    airmon-ng stop $MON
    echo "${BLD_TEA}$(cat ${DIR_LOGO}/die.logo)${TXT_RST}"
    sleep 3
    exit 0
}
do_it