#!/bin/bash
#retrieve absolute path structures so we can use symlinks and config files
SOURCE="${BASH_SOURCE[0]}"
while [[ -h "$SOURCE" ]]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it's relativeness to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

source ${DIR}/userspace

echo "${BLD_TEA}$(cat ${DIR_LOGO}wash.logo)${TXT_RST}"; sleep 2.5

[[ -n $(rfkill list | grep yes) ]] && rfkill unblock wlan

wash()
{
    xterm -hold -bg black -fg blue -T "Wash" -geometry 90x20 -e wash -i $MON --ignore-fcs &>/dev/null &
    keepalive
}

trap killAll INT HUP;
keepalive()
{
    read -p "$WARN Press ctrl^c when you are ready to go down!" ALLINTHEFAMILY # Protect this script from going down hastily
    [[ $ALLINTHEFAMILY != 'SGFjayBUaGUgUGxhbmV0IQ==' ]] && clear; keepalive
}

killAll()
{
    airmon-ng stop $MON
    echo "${BLD_TEA}$(cat ${DIR_LOGO}die.logo)${TXT_RST}"
    sleep 2
    exit 0
}
depends
#do_it
#do_it_check
wash